apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-service
  namespace: nestjs-k8s
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: api
  type: LoadBalancer
