apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: nestjs-k8s
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
