apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: nestjs-k8s
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
