apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: nestjs-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        date: {{ now | unixEpoch }}
      name: api
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secret
          image: us-central1-docker.pkg.dev/nestjs-k8s-436002/nestjs-k8s/production:latest
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 3000
      restartPolicy: Always
