apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nestjs-k8s
  labels:
    app: postgres-database
spec:
  selector:
    app: postgres-database
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
