apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
  namespace: nestjs-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
      name: postgres-database
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: secret
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: config
          image: postgres:13-alpine
          name: postgres-database
          ports:
            - containerPort: 5432
